### ISSUE TITLE
options is not defined

### ISSUE THREAD

**Issue by AmirRaptoR** [djfdyuruiry/swagger2-to-object#1]
I`m using [swagger2-to-postman](https://github.com/djfdyuruiry/swagger2-postman-generator) which depends on this library. The new version is not working because of this error

> ReferenceError: options is not defined

I managed to resolve error by adding option to **buildSwaggerRefsLookup** method. Maybe it helps.
There are other references to this method and i`m not good with javascript so i didn't send pull request.

**Comment by djfdyuruiry** [comment]
Hey @AmirRaptoR 

Yeah wrong versions pushed to npm, all has been fixed and pushed to npm, so should be good now :)
